import styles from "../../styles/Home.module.css";
import Head from "next/head";
import {useRouter} from "next/router";

const SayHelloPage = () => {
  const {query} = useRouter()
  const {name} = query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello, {name}
        </h1>

        <div className={styles.grid}>
          <a href="/" className={styles.card}>Back</a>
        </div>
      </main>
    </div>
  )
}

export default SayHelloPage;